### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by KegenGuyll** [Lewis-Hamilton/react-login#2]
- [ ] Must be able to create/login an account
- [ ] Must be able to create a todo item
- [ ] Todo item must contain a title and a description
- [ ] Must be able to edit title and/or description
- [ ] Must be able to remove an item
- [ ] Must be able to refresh and still be able to see todo items
